version: '3.8'

services:
  mynotinhas_backend:
    image: wesleyscorrea/mynotinhas_backend:0.1
    container_name: my-notinhas_backend
    ports:
      - "8090:8090"
    environment:
      SERVER_PORT: 8090
      SERVLET_CONTEXT_PATH: /api
      DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/MyNotinhas
      DATASOURCE_USERNAME: MyNotinhas
      DATASOURCE_PASSWORD: Project2024
      GOOGLE_CLIENT_ID: 291704101729-tu7ghdk6ccd08f78rugpq8o22ji89jv3.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
    depends_on:
      - postgres_db
    networks:
      - my-notinhas_network

  postgres_db:
    image: postgres
    container_name: my-notinhas_database
    environment:
      POSTGRES_DB: MyNotinhas
      POSTGRES_USER: MyNotinhas
      POSTGRES_PASSWORD: Project2024
    ports:
      - "5432:5432"
    networks:
      - my-notinhas_network

networks:
  my-notinhas_network:
